name: Build and Deploy ASP.NET Web Forms to IIS

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: windows-latest
    env:
      SOLUTION_FILE: PTSCOATING.sln
      PROJECT_FILE: PTSCOATING.csproj
      PUBLISH_DIR: ${{ github.workspace }}\publish
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v2

      - name: Restore NuGet packages
        run: msbuild $env:SOLUTION_FILE /t:Restore

      - name: Build solution
        run: msbuild $env:SOLUTION_FILE /p:Configuration=Release

      - name: Publish
        run: msbuild PTSCOATING.csproj /p:Configuration=Release /p:DeployOnBuild=true /p:WebPublishMethod=FileSystem /p:PublishUrl=publish

      - name: Deploy to IIS with msdeploy
        shell: pwsh
        run: |
          & "C:\Program Files\IIS\Microsoft Web Deploy V3\msdeploy.exe" `
            -source:package=".\publish\PTSCOATING.zip" `
            -dest:iisApp="$env:IIS_SITE_NAME",ComputerName="https://$env:IIS_SERVER:8172/msdeploy.axd?site=$env:IIS_SITE_NAME",UserName="$env:IIS_USERNAME",Password="$env:IIS_PASSWORD",AuthType="Basic" `
            -verb:sync `
            -allowUntrusted
        env:
          IIS_SITE_NAME: 'YourSiteName'
          IIS_SERVER: 'your.server.com'
          IIS_USERNAME: 'your-username'
          IIS_PASSWORD: ${{ secrets.IIS_PASSWORD }}
