name: Build and Deploy ASP.NET Web Forms to IIS

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: windows-latest
    env:
      SOLUTION_FILE: PTSCOATING.sln
      PROJECT_FILE: PTSCOATING.csproj
      PUBLISH_DIR: E:\COATINGPTS\publish
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v2

      - name: Restore NuGet packages
        run: msbuild $env:SOLUTION_FILE /t:Restore

      - name: Build solution
        run: msbuild $env:SOLUTION_FILE /p:Configuration=Release

      - name: Publish web project
        run: |
          msbuild $env:PROJECT_FILE /p:Configuration=Release /p:WebPublishMethod=FileSystem /p:PublishUrl=${{ env.PUBLISH_DIR }} /t:WebPublish
          if (!(Test-Path -Path $env:PUBLISH_DIR)) { Write-Error "Publish directory not found: $env:PUBLISH_DIR"; exit 1 }
        
      - name: Deploy to IIS via Web Deploy
        run: |
          & "C:\Program Files\IIS\Microsoft Web Deploy V3\msdeploy.exe" `
            -verb:sync `
            -source:contentPath="${{ env.PUBLISH_DIR }}" `
            -dest:iisApp='${{ secrets.IIS_SITE_NAME }}',ComputerName='https://${{ secrets.IIS_SERVER }}:8172/msdeploy.axd?site=${{ secrets.IIS_SITE_NAME }}',UserName='${{ secrets.IIS_USERNAME }}',Password='${{ secrets.IIS_PASSWORD }}',AuthType='Basic' `
            -allowUntrusted
        env:
          IIS_SERVER: ${{ secrets.IIS_SERVER }}
          IIS_SITE_NAME: ${{ secrets.IIS_SITE_NAME }}
          IIS_USERNAME: ${{ secrets.IIS_USERNAME }}
          IIS_PASSWORD: ${{ secrets.IIS_PASSWORD }}
