name: Build and Deploy ASP.NET Web Forms to IIS

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: windows-latest
    env:
      SOLUTION_FILE: PTSCOATING.sln
      PROJECT_FILE: PTSCOATING.csproj
      PUBLISH_DIR: ${{ github.workspace }}\publish
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v2

      - name: Restore NuGet packages
        run: msbuild $env:SOLUTION_FILE /t:Restore

      - name: Build solution
        run: msbuild $env:SOLUTION_FILE /p:Configuration=Release

      - name: Publish web project
        run: msbuild $env:PROJECT_FILE /p:DeployOnBuild=true /p:WebPublishMethod=FileSystem /p:Configuration=Release /p:PublishDir=${{ env.PUBLISH_DIR }}

      - name: Deploy to IIS via Web Deploy
        run: >
          msdeploy.exe
          -source:package='${{ env.PUBLISH_DIR }}'
          -dest:auto,ComputerName='https://${{ secrets.IIS_SERVER }}:8172/msdeploy.axd?site=${{ secrets.IIS_SITE_NAME }}',UserName='${{ secrets.IIS_USERNAME }}',Password='${{ secrets.IIS_PASSWORD }}',AuthType='Basic'
          -verb:sync
          -allowUntrusted
        env:
          IIS_SERVER: ${{ secrets.IIS_SERVER }}
          IIS_SITE_NAME: ${{ secrets.IIS_SITE_NAME }}
          IIS_USERNAME: ${{ secrets.IIS_USERNAME }}
          IIS_PASSWORD: ${{ secrets.IIS_PASSWORD }}
